stages:
  - generate_changelog

changelog:
  stage: generate_changelog
  image: registry.gitlab.com/gitlab-org/release-tools/gitlab-changelog:latest
  script:
    - generate-changelog > CHANGELOG.md
  artifacts:
    paths:
      - CHANGELOG.md
  only:
    - tags
